In [11]:
import numpy as np
import pandas as pd
#------ Using List,Dictionary,if,elif,else,loops----
students = [
     {'Id': 101,'Name':'Raju','Marks':[70,80,50]},
     {'Id': 102,'Name':'Raghu','Marks':[90,50,60]},
     {'Id':103,'Name': 'Meena', 'Marks':[50,60,35]},
     {'Id':104,'Name': 'Sanju', 'Marks':[60,20,40]},
     {'Id' :105,'Name': 'Suraj','Marks' : [90,80,80]},
    ]
print("=== Student Grades ===")
for s in students:
    avg = sum(s["Marks"]) / len(s["Marks"])
    if avg >= 85:
        grade = "A"
    elif avg >= 70:
        grade = "B"
    elif avg >= 50:
        grade = "C"
    else:
        grade = "Fail"
    print(f"{s['Name']} - Avg: {avg:.2f} - Grade: {grade}")

# ---------- Part 2: NumPy Operations ----------
print("\n=== NumPy Array Operations ===")

# Create a NumPy array of marks
Marks_arr = np.array([[70,80,50],
                     [90,50,60],
                     [50,60,35],
                     [60,20,40],
                     [90,80,80]])
# Aggregate functions
print("Total Marks per student:" , np.sum(Marks_arr,axis = 0))
print("Highest Marks:",np.max(Marks_arr,axis = 0))
print("Lowest Marks:", np.min(Marks_arr,axis =0))
print("Average Marks:", np.mean(Marks_arr,axis = 0))
#Reshape
reshaped = np.arange(15).reshape(3,5)
print("\nReshaped Array (4x3):")
print(reshaped)

#pandas
data ={
     "Id" : [101,102,103,104,105],
     "Name" : ["Raju","Raghu","Meena","Sanju","Suraj"],
     "Marks Total" :[200,200,145,120,250]
}
df = pd.DataFrame(data)
df.to_csv(r"C:\Users\Hp\OneDrive\Desktop\studentss.csv",index = False)
print("OK! After Saving the File")

# Aggregation & Grouping
# Let's simulate grouping by performance (High, Medium, Low)
# Define performance category function
def performance_category(marks_total):
    if marks_total >= 200:
        return "High"
    elif marks_total >= 130:
        return "Medium"
    else:
        return "Low"

# Apply function
df["Performance"] = df["Marks Total"].apply(performance_category)

print("=== Updated DataFrame ===")
print(df)

# Group by Performance
print("\n=== Grouping by Performance ===")
print(df.groupby("Performance")[["Marks Total"]].mean())

#pandas sales_data
sales_data = {
              "orderId" : [1,2,3,4,5,6,7,8],
              "product": ["Laptop","Mouse", "Pen","Chair","table","book","keyboard","speaker"],
              "category" : ["Electronics",  "Electronics","Sationary","Furniture","furniture","Sationery","Electronics","Electronics"],
              "Sales" :[2000,4000,500,5000,800,900,None,900],
              "Quantity":[2,1,2,4,1,2,3,4],
              "Profit":[800,500,400,500,None,200,400,900]
}
df = pd.DataFrame(sales_data)
df.to_csv(r"C:\Users\Hp\OneDrive\Desktop\sales_data.csv",index = False)
print("OK! After Saving the File")
print("\n=== Sales Data ===")
print(df)
print("\nSorted by Sales (Descending):")
print(df.sort_values(by="Sales", ascending=False))

# --- Aggregation & Grouping ---
# Group by Category and find total sales & average profit

grouped = df.groupby("category")[["Sales","Profit"]].agg(["sum","mean"])
print("\nGrouped by Category (Total & Avg):")
print(grouped)




=== Student Grades ===
Raju - Avg: 66.67 - Grade: C
Raghu - Avg: 66.67 - Grade: C
Meena - Avg: 48.33 - Grade: Fail
Sanju - Avg: 40.00 - Grade: Fail
Suraj - Avg: 83.33 - Grade: B

=== NumPy Array Operations ===
Total Marks per student: [360 290 265]
Highest Marks: [90 80 80]
Lowest Marks: [50 20 35]
Average Marks: [72. 58. 53.]

Reshaped Array (4x3):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
OK! After Saving the File
=== Updated DataFrame ===
    Id   Name  Marks Total Performance
0  101   Raju          200        High
1  102  Raghu          200        High
2  103  Meena          145      Medium
3  104  Sanju          120         Low
4  105  Suraj          250        High

=== Grouping by Performance ===
             Marks Total
Performance             
High          216.666667
Low           120.000000
Medium        145.000000
OK! After Saving the File

=== Sales Data ===
   orderId   product     category   Sales  Quantity  Profit
0        1    Laptop  Electronics  2000.0  